### ISSUE TITLE
`test` command

### ISSUE THREAD

**Issue by intsuc** [mcenv/mcx#35]
```[tasklist]
### Tasks
- [ ] https://github.com/mcenv/mcx/issues/51
- [ ] https://github.com/mcenv/mcx/issues/26
- [ ] https://github.com/mcenv/mcx/issues/28
```

**Comment by intsuc** [comment]
https://github.com/mcenv/mcx/commit/1a8971e617b707d98f4e63d1c913f3a87def48cd
